
assoc_words=function(cleaned_ngram,type_word,min_occurence=5){
  # from the table of ngrams generated by clean_ngram() find the most common associated words by 
  # typology:
  
  #parameters:
  # clean_ngram: output from clean_ngram()
  # type_word: the name of the category to analyse (check outptu of clean_ngram() to see the available list)
  # min_occurence: only display the words with at least this specified number of occurence
  dt= cleaned_ngram %>% 
    dplyr::filter(get(type_word)==1) %>% grou
  tidyr::separate(word, "list_nwords", sep = " ") %>% tidyr::gather() %>% dplyr::filter(value!="") %>% dplyr::group_by(value) %>% 
    dplyr::summarize(n=n()) %>% dplyr::filter(!stringr::str_detect(value,"\\d"))%>% dplyr::arrange(-n) %>% dplyr::rename(word=value)
  
  dt=dt %>% dplyr::filter(!is.na(word) & word!="" & n>min_occurence)
  return(dt)
}
